# Generated by Django 5.2.14 on 2026-09-03 02:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('metodo_contato', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=10, verbose_name='Método de contato preferido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('whatsapp', models.CharField(blank=True, help_text='Armazenado normalizado no formato +55DDXXXXXXXXX.', max_length=20, null=True, verbose_name='WhatsApp')),
                ('tipo_projeto', models.CharField(choices=[('landing_page', 'Landing Page'), ('site_institucional', 'Site Institucional'), ('ecommerce', 'E-commerce'), ('sistema_web', 'Sistema Web'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de projeto')),
                ('descricao', models.TextField(verbose_name='Descrição do projeto')),
                ('orcamento_faixa', models.CharField(blank=True, choices=[('ate_2k', 'Até R$ 2.000'), ('de_2k_a_5k', 'R$ 2.000 – R$ 5.000'), ('de_5k_a_10k', 'R$ 5.000 – R$ 10.000'), ('acima_10k', 'Acima de R$ 10.000'), ('nao_sei_ainda', 'Ainda não sei')], max_length=20, null=True, verbose_name='Faixa de orçamento')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_contato', 'Em contato'), ('convertido', 'Convertido'), ('descartado', 'Descartado')], default='novo', max_length=15, verbose_name='Status')),
                ('origem', models.CharField(default='portfolio', max_length=50, verbose_name='Origem')),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-criado_em'],
            },
        ),
    ]
